
seed: 0
predictor: gcn #gbdt # feedforward
dataset: cifar10
out_dir: run

train_size: 50
test_size: 100

# Used by Jacobian_cov from NAS without training from DARTS for data loader
search:
  batch_size: 256 # modified based on NAS with training paper
  data_size: 25000
  cutout: False
  cutout_length: 16
  cutout_prob: 1.0
