
search_space: darts
predictor: sotl
test_size: 1000
seed: 0

dataset: cifar10
out_dir: run
single_run: True

trainable:
    train_size_single: 50
    train_size_start: 10
    train_size_end: 200
    train_size_increment: 10

learning_curve:
    fidelity_single: 50
    fidelity_start: 10
    fidelity_end: 200
    fidelity_increment: 10
