
# experiment types: single, vary_train_size, vary_fidelity
experiment_type: vary_train_size
search_space: nasbench201
predictor: feedforward
test_size: 100
seed: 0

dataset: cifar10
out_dir: run

train_size_start: 10
train_size_end: 210
train_size_increment: 10

fidelity_start: 10
fidelity_end: 190
fidelity_increment: 10

# Used by Jacobian_cov from NAS without training from DARTS for data loader
search:
  batch_size: 256 # modified based on NAS with training paper
  data_size: 25000
  cutout: False
  cutout_length: 16
  cutout_prob: 1.0
  train_portion: 0.7

