
# set load_labeled to True for darts, and False for nasbench201
search_space: darts
load_labeled: True
seed: 0
predictor: feedforward
dataset: cifar10
out_dir: run

train_size: 100
test_size: 300
dataset: cifar10

