config_id: 6
dataset: TIMIT
optimizer: rs
out_dir: run_cpu
search:
  acq_fn_optimization: random_sampling
  acq_fn_type: its
  checkpoint_freq: 5000
  debug_predictor: false
  encoding_type: path
  epochs: 200
  fidelity: -1
  k: 18
  max_mutations: 11
  num_arches_to_mutate: 1
  num_candidates: 48
  num_ensemble: 3
  num_init: 61
  population_size: 8
  predictor: var_sparse_gp
  sample_size: 29
search_space: asr
seed: 3
