config_id: 88
dataset: TIMIT
optimizer: rs
out_dir: run_cpu
search:
  acq_fn_optimization: random_sampling
  acq_fn_type: its
  checkpoint_freq: 5000
  debug_predictor: false
  encoding_type: path
  epochs: 200
  fidelity: -1
  k: 19
  max_mutations: 5
  num_arches_to_mutate: 9
  num_candidates: 44
  num_ensemble: 3
  num_init: 21
  population_size: 66
  predictor: var_sparse_gp
  sample_size: 83
search_space: asr
seed: 5
