config_id: 47
dataset: TIMIT
optimizer: rs
out_dir: run_cpu
search:
  acq_fn_optimization: random_sampling
  acq_fn_type: its
  checkpoint_freq: 5000
  debug_predictor: false
  encoding_type: path
  epochs: 200
  fidelity: -1
  k: 13
  max_mutations: 15
  num_arches_to_mutate: 8
  num_candidates: 28
  num_ensemble: 3
  num_init: 30
  population_size: 73
  predictor: var_sparse_gp
  sample_size: 52
search_space: asr
seed: 7
