
# nasbench101, nasbench201, darts, nlp, transbench101
search_space: transbench101

# nasbench201 datasets: cifar10, cifar100, ImageNet16-120
# transbench101 datasets: class_scene
dataset: class_scene

# random seed (only important for autocorrelation)
seed: 1000

# stats that can be computed by iterating through
# all architectures in the search space
run_acc_stats: True
max_set_size: 100

# compute the average nbhd size
run_nbhd_size: True
max_nbhd_trials: 5

# autocorrelation parameters
run_autocorr: True
max_autocorr_trials: 5
autocorr_size: 36
walks: 100
